version: '3.8'

services:
  smart-mermaid:
    container_name: smart-mermaid
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.env.local:/app/.env.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped
